---
all:
  vars:
    ansible_python_interpreter: "/home/user/Ansible-MultiVendor-PS/venv/bin python"
  children:
    netbox_servers:
      vars:
        ansible_connection: "ansible.builtin.local"
      hosts:
        netbox1:
          ansible_host: "10.0.10.40"

