---
all:
  children:
    ios_switches:
      hosts:
        S2:
          ansible_host: "10.0.10.2"
    nxos_switches:
      hosts:
        S3:
          ansible_host: "10.0.10.3"
    eos_switches:
      hosts:
        S4:
          ansible_host: "10.0.10.4"
