---
- name: "Test dynamic Inventory using Netbox Plugin"
  hosts: "device_roles_switch"
  connection: "ansible.builtin.local"
  tasks:

    - name: "Reveal discovered host and network os"
      ansible.builtin.debug:
        msg: "{{ ansible_host }} / {{ ansible_network_os }}"

    - name: "Attempt to ping the ansible_host from control node"
      ansible.builtin.command: "ping -c 2 -w 5 {{ ansible_host }}"
      changed_when: false
